/* Users constants */
module.exports = {
  // LOGIN ACTIONS
  'LOGIN_REQUEST': 'LOGIN_REQUEST',
  'LOGIN_SUCCESS': 'LOGIN_SUCCESS',
  'LOGIN_FAILURE': 'LOGIN_FAILURE',
  // SIGN UP ACTIONS
  'SIGNUP_REQUEST': 'SIGNUP_REQUEST',
  'SIGNUP_SUCCESS': 'SIGNUP_SUCCESS',
  'SIGNUP_FAILURE': 'SIGNUP_FAILURE',
  // EVENTS ACTIONS
  'FETCH_EVENTS_REQUEST': 'FETCH_EVENTS_REQUEST',
  'FETCH_EVENTS_SUCCESS': 'FETCH_EVENTS_SUCCESS',
  'FETCH_EVENTS_FAILURE': 'FETCH_EVENTS_FAILURE'
}
